run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace

  disable:
    - typecheck # Can be flaky with generics

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/DiarmuidKelly/astrometry-api-server

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - unparam

    # Exclude certain revive rules
    - linters:
        - revive
      text: "should have a package comment"
